### ISSUE TITLE
XMLA doesn't seem to work

### ISSUE THREAD

**Issue by mrkazoodle** [OSBI/saiku#610]
Hi,

I did a fresh install of Saiku CE 3.15 on Ubuntu 16.04 and tried to connect from ms excel 2010 32bit on a Windows 7 64bit pc.
I got an error mentioning "isplaceholder" (for an out of the box example), after connecting and whilst trying to consult tree data.
Also I could only see one catalog, even though there are multiple connections.

Is XMLA still supported? If so, please check if you can reproduce me error.

Thanks in advance

**Comment by buggtb** [comment]
bits are available but pretty unmaintained. as you can see YMMV.
