### ISSUE TITLE
Can't remove datasources

### ISSUE THREAD

**Issue by buggtb** [OSBI/saiku#612]
In the Admin Console, if I delete the Data Sources and Schemas and restart, the deleted items re-appear (they can also be selected in Cubes) Also, removing the schmea does not even remove it from the list of schemas.

**Comment by schoeso** [comment]
Sehr geehrte Damen und Herren,

ich bin derzeit nicht im Büro, werde aber so schnell wie möglich auf Ihre Anfrage reagieren. Am 03.01.2018 bin ich wieder zurück.

Mit freundlichen Grüßen

Dr. Arndt Schönberg

**Comment by brunogamacatao** [comment]
Datasource removal is working on the three different repositories implementations (filebased, jackrabbit and marklogic)
