### ISSUE TITLE
Parsing different date formats should be supported

### ISSUE THREAD

**Issue by buggtb** [OSBI/saiku#613]
When importing a CSV, dates in dd/mm/yyyy format throw an exception:

CompileException: Line 10, Column 69: No applicable constructor/method found for actual parameters "java.lang.Object"; candidates are: "public static java.sql.Date org.apache.calcite.runtime.SqlFunctions.internalToDate(java.lang.Integer)", "public static java.sql.Date org.apache.calcite.runtime.SqlFunctions.internalToDate(int)"

We should support different formats, but realign them all to yyyy/MM/dd

**Comment by buggtb** [comment]
This is related to saikueecore issue 17

**Comment by brunogamacatao** [comment]
Currently, we support the following date formats:
MM/dd/yyyy
dd/MM/yyyy
yyyy/MM/dd
yyyy-MM-dd
MM.dd.yyyy
dd.MM.yyyy
