### ISSUE TITLE
Detection of dollar amounts in schema..

### ISSUE THREAD

**Issue by buggtb** [OSBI/saiku#614]
Interesting one:

Does not parse dollar amount ($xx.xx) as a measure.

**Comment by buggtb** [comment]
We should detect currency symbols at the start of the field and if so, add the symbol to the heading name and make the field a numeric

**Comment by brenopolanski** [comment]
I should remove the symbol `$` when create a measure?

**Comment by brenopolanski** [comment]
Moved to gitlab!
