### ISSUE TITLE
clicking the mdx query button doesn't copy the old query into the window

### ISSUE THREAD

**Issue by buggtb** [OSBI/saiku#617]
This might be due to the change I asked for the other week, if I click on the mdx query button it used to copy the mdx into the query panel, now its empty

**Comment by brenopolanski** [comment]
I dont see this bug:

![screenshot from 2018-01-07 15-38-19](https://user-images.githubusercontent.com/1894191/34652733-eb8417ee-f3c0-11e7-978d-cf5d2de24257.png)

![screenshot from 2018-01-07 15-37-59](https://user-images.githubusercontent.com/1894191/34652736-f15dd042-f3c0-11e7-84d4-ab2956a4b640.png)

The modification the other week not make this mdx into the query panel empty. See: https://github.com/OSBI/saiku/commit/194b1b59c57ce93cc669ba737a9008aa7995d6e5
