### ISSUE TITLE
User rights check after expiry

### ISSUE THREAD

**Issue by mrkazoodle** [OSBI/saiku#620]
### Is this a bug report?

Yes

### Environment

1. `java -version`:
2. `node -v` (If you use Node.js proxy for Saiku):
3. `npm -v` (If you use Node.js proxy for Saiku):
4. `yarn --version` (If you use Node.js proxy for Saiku and if you use Yarn):

Then, specify:

1. Operating system:
2. Browser and version (if relevant):
3. Saiku plugin to Pentaho or Saiku Standalone: standalone
4. Saiku CE or Saiku EE: CE
5. Saiku version: 3.15

### Steps to Reproduce

(Write your steps here:)

1. Log in with admin account
2. Wait for the session to expire
3. Do something in order to trigger the pop-up requesting to log in again
4. Log in with a non admin account
5. Access the admin panel

### Expected Behavior

The admin button should have disappeared.
If open, the admin panel should be closed (not tested).
Maybe access to some data marts or cubes should be blocked as well (not verified).

### Actual Behavior

Access to the admin panel is possible: I successfully tested if I could upload a schema file. A user could thus change the schema grants for example.

**Comment by buggtb** [comment]
Interesting. Most admin endpoints check for admin roles. Schema upload may not, I'll check.
