### ISSUE TITLE
Cube drop-down menu selection

### ISSUE THREAD

**Issue by mrkazoodle** [OSBI/saiku#623]
### Is this a bug report?

Yes

### Environment

1. `java -version`: openjdk 1.8.0_151
2. `node -v` (If you use Node.js proxy for Saiku):
3. `npm -v` (If you use Node.js proxy for Saiku):
4. `yarn --version` (If you use Node.js proxy for Saiku and if you use Yarn):

Then, specify:

1. Operating system: Ubuntu 16.04 LTS
2. Browser and version (if relevant): Firefox 58.0 (64-bits)
3. Saiku plugin to Pentaho or Saiku Standalone: Standalone
4. Saiku CE or Saiku EE: CE
5. Saiku version: 3.15

### Steps to Reproduce

(Write your steps here:)

1. Open query & select a cube
2. Select a different cube
3. Click "Cancel" in the pop-up "New Query" which warns about clearing the existing query

### Expected Behavior

The name of the first cube should be shown: the change to the other cube was cancelled.

### Actual Behavior

The selected cube has changed to the second cube (= wrong).

**Comment by brenopolanski** [comment]
hey @mrkazoodle. I fixed the bug (commit: https://github.com/OSBI/saiku/commit/75ed377e532e604c22dd63ac481b734f09f53519)! Thanks :D
