### ISSUE TITLE
bigquery

### ISSUE THREAD

**Issue by rikima** [OSBI/saiku#625]
### Is this a bug report?

(write your answer here)

### Environment

1. `java -version`:
2. `node -v` (If you use Node.js proxy for Saiku):
3. `npm -v` (If you use Node.js proxy for Saiku):
4. `yarn --version` (If you use Node.js proxy for Saiku and if you use Yarn):

Then, specify:

1. Operating system:
2. Browser and version (if relevant):
3. Saiku plugin to Pentaho or Saiku Standalone:
4. Saiku CE or Saiku EE:
5. Saiku version:

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Please add screenshots!)

**Comment by brenopolanski** [comment]
@rikima bigquery? What do you mean by that? Can you edit this issue please?

**Comment by brenopolanski** [comment]
Closing this due to its inactivity...
