### ISSUE TITLE
Can't create license

### ISSUE THREAD

**Issue by thalesmello** [OSBI/saiku#626]
Hello.

I'm having trouble creating a community edition license.

The server appears to not be responding whenever I try to create a license at

https://licensing.meteorite.bi/licenses?form

Is everything working properly?

**Comment by brenopolanski** [comment]
Hey @thalesmello I tested now and worked fine with me. Have you some screenshot?

**Comment by thalesmello** [comment]
Hi. Thanks for the quick answer.

I managed to successfully create a license at the end. The problem was that I must have a company created before I'm able to create a new license. 

The problem here is that I had no feedback that was necessary, not an error message or anything. The page just hangs until there is a timeout. Maybe it could be improved to avoid errors such as this.

Thanks for the attention. I'm closing this issue as it's no longer a problem.

**Comment by brenopolanski** [comment]
Nice @thalesmello 

Thanks for your feedback!

**Comment by daveRanjan** [comment]
Not working again!
