### ISSUE TITLE
In Firefox filenames with spaces are truncated upon download

### ISSUE THREAD

**Issue by enricomariam42** [OSBI/saiku#634]
### Is this a bug report?

yes

### Environment

1. `java -version`:
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

2. `node -v` (If you use Node.js proxy for Saiku):
3. `npm -v` (If you use Node.js proxy for Saiku):
4. `yarn --version` (If you use Node.js proxy for Saiku and if you use Yarn):

Then, specify:

1. Operating system:
server:
Linux biserver 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
2. Browser and version (if relevant):
Firefox Quantum
58.0.2 (64 bit) (affect all Firefox version)
3. Saiku plugin to Pentaho or Saiku Standalone:
Saiku plugin p7.1-3.17-SNAPSHOT
4. Saiku CE or Saiku EE:
Saiku CE
5. Saiku version:
3.17-SNAPSHOT (affects all)

### Steps to Reproduce

(Write your steps here:)

1. In Firefox open a saved saiku query with space in path or query name
![browse_query](https://user-images.githubusercontent.com/4611287/36384771-b51d63e4-1590-11e8-886c-15c9293d44e3.png)
2. Click in one of the Export button (xls, csv or pdf)

### Expected Behavior

The file name should contain the entire query name
![export_xls_ok](https://user-images.githubusercontent.com/4611287/36384767-b4bbfeec-1590-11e8-8dca-624741d510d3.png)

### Actual Behavior

 The file name are truncated on first space
![export_xls](https://user-images.githubusercontent.com/4611287/36384768-b4d2f796-1590-11e8-8cb4-7afb0249d08f.png)
![export_pdf](https://user-images.githubusercontent.com/4611287/36384769-b4ea5404-1590-11e8-82f8-852d0f6e6ddd.png)
![export_csv](https://user-images.githubusercontent.com/4611287/36384770-b50581a2-1590-11e8-9b72-a43965fe032d.png)

### Note
Is a known behaviour, see:
http://kb.mozillazine.org/Filenames_with_spaces_are_truncated_upon_download
The fix: put extra quotes around the filename
https://bugzilla.mozilla.org/show_bug.cgi?id=221028#c61
like
header("Content-Disposition: attachment; filename=\"".basename($file)."\"");

**Comment by brenopolanski** [comment]
Merged #636 
Thanks @enricomariam42 :+1:
