### ISSUE TITLE
Query view Rows | Measures

### ISSUE THREAD

**Issue by mrkazoodle** [OSBI/saiku#638]
### Is this a bug report?

Yes.

### Environment

1. `java -version`: openjdk 1.8.0_151
2. `node -v` (If you use Node.js proxy for Saiku):
3. `npm -v` (If you use Node.js proxy for Saiku):
4. `yarn --version` (If you use Node.js proxy for Saiku and if you use Yarn):

Then, specify:

1. Operating system: Ubuntu 16.04 LTS server, Windows 7 professional client
2. Browser and version (if relevant): Firefox 58.0.2 (64-bits)
3. Saiku plugin to Pentaho or Saiku Standalone: Standalone
4. Saiku CE or Saiku EE: CE
5. Saiku version: 3.15

### Steps to Reproduce

(Write your steps here:)

1. Make a query with multiple measures
2. Click on the 'measures' block's heading and select the position "Rows | Measures"

### Expected Behavior

(Write what you thought would happen.)
Readable output

### Actual Behavior

(Write what happened. Please add screenshots!)

All of the values of the attributes selected in the 'Rows' block are displayed under the attribute names of the attributes selected in the 'Columns' block.
The values of the last attribute selected in the 'Columns' block are shifted to the right by the number of attributes in the 'Rows' block.

Column Attribute1 |        value1.1         | value1.2 | ...
Column Attribute2 | Row Attribute1 | Row Attribute2 | Measures | value2.1 | value2.2 | value3 |...
Value1.1 | value2.1 | Measure1 | measure value for respective attribute values | ...
...

Solution: empty space

Column Attribute1 |        value 1         | value2 | ...
Column Attribute2 | value 1 | value2 | value3 |...
Row Attribute1 | Row Attribute2 | Measures | empty space
Value1 | value1 | measure1 | measure value X | ...
...

**Comment by brenopolanski** [comment]
Hey @mrkazoodle thanks again! I fixed this issue https://github.com/OSBI/saiku/commit/c0d92f324b44e94415b55e716f5e30a926b5766c
