### ISSUE TITLE
Can Saiku   surpport  the function -"array join"  

### ISSUE THREAD

**Issue by zgbook** [OSBI/saiku#644]
Qusetion:
Can Saiku   surpport  the function --"arrayJoin"  ?
(there are many values in a  member of a dimenssion )

s|arr
----|----
Hello | [1,2] 
World | [3,4,5] 
Goodbye | [ ]

When i use: `<SQL dialect="clickhouse">arrayJoin(`arr`)</SQL>` in my *.xml,
I got this: `java.sql.SQLFeatureNotSupportedException`

**Comment by buggtb** [comment]
Not without something like a Mondrian UDF

**Comment by ART-jason** [comment]
do you make it?I also want to use clickhouse in saiku,but the saiku cant support clickhouse i think now
