### ISSUE TITLE
Problem with builds

### ISSUE THREAD

**Issue by averholantsev** [OSBI/saiku#678]
We have some problems with version building 

The problem is connected with the "moving" site https://repo.pentaho.org/
The pom-files of the current versions (develop and 3.90) indicate this site. The  404 code is returned  after accessing this resources. 
------------------------------------------------------------------------------------------
java -version:
$ java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

$ mvn --version
Apache Maven 3.3.3 (NON-CANONICAL_2016-02-12T00:26:22_builder; 2016-02-12T05:26:22+05:00)
Maven home: /usr/share/maven
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-1.b01.x86_64/jre
Default locale: ru_RU, platform encoding: UTF-8
OS name: "linux", version: "4.9.50-un-def-alt0.m80p.1", arch: "amd64", family: "unix"

Operating system: Linux
Browser and version (if relevant): Mozilla, Chrome (not relevant)
Saiku plugin to Pentaho or Saiku Standalone: Saiku plugin to Pentaho
Saiku CE or Saiku EE: Saiku CE
Saiku version: Saiku brahches: - development; - 3.90

**Comment by buggtb** [comment]
Meh, although the repo looks up now

**Comment by averholantsev** [comment]
I forgot to attach:
$mvn compile
...
[ERROR] Failed to execute goal on project saiku-web: Could not resolve dependencies for project org.saikuanalytics:saiku-web:jar:3.17: Failed to collect dependencies at org.apache.xmlgraphics:fop:jar:2.2 -> org.apache.xmlgraphics:batik-awt-util:jar:1.9: Failed to read artifact descriptor for org.apache.xmlgraphics:batik-awt-util:jar:1.9: Could not transfer artifact org.apache.xmlgraphics:batik:pom:1.9 from/to Analytical Labs snapshots (http://repo.meteorite.bi/repository/alabs-snapshot-local/): Failed to transfer file: http://repo.meteorite.bi/repository/alabs-snapshot-local/org/apache/xmlgraphics/batik/1.9/batik-1.9.pom. Return code is: 400 , ReasonPhrase:Repository version policy: SNAPSHOT does not allow version: 1.9. -> [Help 1]

**Comment by lhg-interact** [comment]
Same problem. Any solution?

**Comment by lhg-interact** [comment]
It's working now.

**Comment by dbendlin** [comment]
Can't build saiku, I have checkout saiku today:
`git clone https://github.com/OSBI/saiku.git`

Build tools:
`
Maven home: /opt/apache-maven-3.6.0
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: es_PY, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-8-amd64", arch: "amd64", family: "unix"
`

Build Results when running mvn clean install -DskipTests
`
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Saiku Module Project 3.17:
[INFO] 
[INFO] Saiku Module Project ............................... SUCCESS [  5.809 s]
[INFO] saiku - core libraries ............................. SUCCESS [  1.513 s]
[INFO] saiku olap util .................................... FAILURE [  0.594 s]
[INFO] saiku - services ................................... SKIPPED
[INFO] saiku - web ........................................ SKIPPED
[INFO] saiku-ui ........................................... SKIPPED
[INFO] saiku - webapp ..................................... SKIPPED
[INFO] saiku-server ....................................... SKIPPED
[INFO] saiku biserver plugin .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.782 s
[INFO] Finished at: 2019-02-13T00:26:03-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project saiku-olap-util: Compilation failure: Compilation failure: 
[ERROR] error: error reading /home/dbendlin/.m2/repository/pentaho/mondrian/4.3.0.1.1-SPARK/mondrian-4.3.0.1.1-SPARK.jar; error in opening zip file
[ERROR] error: error reading /home/dbendlin/.m2/repository/eigenbase/eigenbase-properties/1.1.0.10924/eigenbase-properties-1.1.0.10924.jar; error in opening zip file
[ERROR] error: error reading /home/dbendlin/.m2/repository/eigenbase/eigenbase-resgen/1.3.0.11873/eigenbase-resgen-1.3.0.11873.jar; error in opening zip file
[ERROR] error: error reading /home/dbendlin/.m2/repository/eigenbase/eigenbase-xom/1.3.0.11999/eigenbase-xom-1.3.0.11999.jar; error in opening zip file
[ERROR] error: error reading /home/dbendlin/.m2/repository/org/olap4j/olap4j-xmla/1.2.0/olap4j-xmla-1.2.0.jar; error in opening zip file
`
I have already deleted those folders inside .m2/repository to make mvn download them again, those poms and jars are been downloaded from remote mvn repos, repo.meteorite.bi seems to be down to


Thanks for your help.

**Comment by EulerYe** [comment]
why http://repo.meteorite.bi/repository/alabs-snapshot-local/ always 503?
