### ISSUE TITLE
[Saiku Enterprise] Bug with the Excel export for report with parameters

### ISSUE THREAD

**Issue by hoti06600** [OSBI/saiku#682]
### Is this a bug report?

Yes

### Environment

1. `java -version`:
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

1. Operating system: CentOS (server where Saiku was installed), MacOS (my computer)
2. Browser and version (if relevant):Firefox 63.0.1 (64 bits)
3. Saiku plugin to Pentaho or Saiku Standalone: Saiku Standalone
4. Saiku CE or Saiku EE:Saiku EE
5. Saiku version: Saiku 3.8.3-EE

### Steps to Reproduce

There are problems with the Excel generated for report having parameters. Also, the CSV generated could not easily be opened in Excel as the fields are separated by comma.

1. Open the "Sales 2" cube from the Foodmart examples
2. Configure the report as following : 
<img width="254" alt="bug_saiku_1" src="https://user-images.githubusercontent.com/44468012/51972868-b43dbb80-247c-11e9-891e-33f4cb241e16.png">

3. If you export to Excel, you will get a document like the following
[bug_saiku_7.xlsx](https://github.com/OSBI/saiku/files/2812044/bug_saiku_7.xlsx)
The document is correct.

4. Add parameter for year, quarter and month
<img width="698" alt="bug_saiku_2" src="https://user-images.githubusercontent.com/44468012/51973202-61183880-247d-11e9-845d-acd54181a94b.png">
<img width="705" alt="bug_saiku_3" src="https://user-images.githubusercontent.com/44468012/51973206-62496580-247d-11e9-93f2-83c227c2acd9.png">
<img width="732" alt="bug_saiku_4" src="https://user-images.githubusercontent.com/44468012/51973210-64132900-247d-11e9-8249-7a6aa1200b34.png">

5. We will have this kind of report : 
<img width="1047" alt="bug_saiku_5" src="https://user-images.githubusercontent.com/44468012/51973366-c10edf00-247d-11e9-9217-0b43d60701f2.png">

6. If you export to Excel, you will get a document like the following
[bug_saiku_6.xlsx](https://github.com/OSBI/saiku/files/2811982/bug_saiku_6.xlsx)

This document has a very weird content. It does not appear like it did in previous versions.

7. If we try to export it to CSV, it could not be easily opened in Excel as the fields are separated by comma. Instead, could the separator be semi-colon ?

**Comment by brunogamacatao** [comment]
This is the Excel report generated following the issue's instructions with the last Saiku version.
[saiku-export.xlsx](https://github.com/OSBI/saiku/files/3308441/saiku-export.xlsx)
