### ISSUE TITLE
License site down

### ISSUE THREAD

**Issue by ruria** [OSBI/saiku#695]
Hello,
community site and licensing are not responding. I can not send a message by contact form on meteorite.bi web, error says:

Notice: Undefined index: field_map_address in include() (line 1 of /var/www/html/sites/all/themes/Porto/templates/node/node--contact.tpl.php).
Warning: stream_socket_enable_crypto(): SSL: Success in SMTP->StartTLS() (line 202 of /var/www/html/sites/all/modules/smtp/smtp.transport.inc).
Unable to send e-mail. Contact the site administrator if the problem persists.

**Comment by brenopolanski** [comment]
Try again @ruria https://licensing.meteorite.bi/login
