### ISSUE TITLE
[Saiku Enterprise] Problem with role

### ISSUE THREAD

**Issue by hoti06600** [OSBI/saiku#701]
### Is this a bug report?

Yes

### Environment

1. `java -version`:
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

1. Operating system: MacOS
2. Browser and version (if relevant):Firefox 67.0.2 (64 bits)
3. Saiku plugin to Pentaho or Saiku Standalone: Saiku Standalone
4. Saiku CE or Saiku EE:Saiku EE
5. Saiku version: Saiku 3.8.3-EE

### Steps to Reproduce

New roles do not work. Only the default roles "ROLE_USER" and "ROLE_ADMIN" work.

1. We modify the already existing "foodmart" data source, using the advanced mode with the content of the file :
[roles_ok.txt](https://github.com/OSBI/saiku/files/3286358/roles_ok.txt)

2. We modify the already existing "foodmart4" schema with the content of the file : 
[foodmart4.txt](https://github.com/OSBI/saiku/files/3286377/foodmart4.txt)

3. We refresh the cubes

4. If we check the logs from the file "saiku.log" we see that some lines appear : 
[log_ok.txt](https://github.com/OSBI/saiku/files/3286402/log_ok.txt)

5. So we understand that the "security.mapping" parameter defined in the datasource is working for the already existing roles "ROLE_USER" and "ROLE_ADMIN".

6. We modify once again the "foodmart" data source with the content of the file :
[roles_nok.txt](https://github.com/OSBI/saiku/files/3286436/roles_nok.txt)

7. We refresh the cubes

8. If we check the logs from the file "saiku.log" we see that some lines appear : 
[log_nok.txt](https://github.com/OSBI/saiku/files/3286463/log_nok.txt)

9. In this case, we have the same lines as before : 
`Setting role to datasource:foodmart role:ROLE_ADMIN,ROLE_USER`

So we understand that the new role "ROLE_TEST" is not taken into account by Saiku.

Indeed, if we try to use the role "ROLE_TEST" in the mondrian schema, it does not work, due to the previous problem.

I could add two roles in a previous version of Saiku EE (downloaded in 2016), but I could not add anymore in the new version. Nonetheless, the two roles created in the previous version still work now. The problem is only about adding new roles.

Maybe, the method of adding role is not correct (perhaps I have forgotten how to do this) ?

Or is it that there is a bug in the new versions of Saiku EE ?

**Comment by brunogamacatao** [comment]
Those issues are fixed in the new version (development branch). 
They are being merged to 3.17 and 3.90 branches.
Here are the exported files with the development branch:
[saiku-export.xlsx](https://github.com/OSBI/saiku/files/3303960/saiku-export.xlsx)
[saiku-export.txt](https://github.com/OSBI/saiku/files/3303962/saiku-export.txt)

**Comment by brunogamacatao** [comment]
It's already fixed at the development branch.
