### ISSUE TITLE
License server down

### ISSUE THREAD

**Issue by tomasWade** [OSBI/saiku#702]
I install latest saiku and get stuck when I visit https://licensing.meteorite.bi for get licenses.
here is the error:
```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.

Reason: Error reading from remote server

Apache/2.4.18 (Ubuntu) Server at licensing.meteorite.bi Port 443
```
My friends who lived in US and EU get same error too.

**Comment by Akaike0** [comment]
True, for me it's down for two days.

**Comment by brenopolanski** [comment]
It's back again @tomasWade @Akaike0 :)

**Comment by tomasWade** [comment]
Thank you very much , It's really great help
