### ISSUE TITLE
question about saiku community version

### ISSUE THREAD

**Issue by suonisisi** [OSBI/saiku#704]
### Is this a bug report?

(write your answer here)

### Environment

1. `java -version`:
2. `node -v` (If you use Node.js proxy for Saiku):
3. `npm -v` (If you use Node.js proxy for Saiku):
4. `yarn --version` (If you use Node.js proxy for Saiku and if you use Yarn):

Then, specify:

1. Operating system:
2. Browser and version (if relevant):
3. Saiku plugin to Pentaho or Saiku Standalone:
4. Saiku CE or Saiku EE:
5. Saiku version:

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Please add screenshots!)

**Comment by suonisisi** [comment]
I was knowing about saiku and feeld it is too powerful. Is it free for users? Why cannot acsess https://community.meteorite.bi/  recently

**Comment by buggtb** [comment]
I'll answer these in order:

> I was knowing about saiku and feeld it is too powerful

Correct... Saiku is too powerful.... try asking @brenopolanski he says its the most powerful tool ever...

> Is it free for users? 

Sure, if you don't want to pay for it.

> Why cannot acsess https://community.meteorite.bi/ recently

No one mentioned it was down and I didn't notice. It is now back up and running.
