### ISSUE TITLE
I can't switch cube in the same query tab

### ISSUE THREAD

**Issue by neolinkbb** [OSBI/saiku#709]
### Is this a bug report?
Yes
### Environment
1. `java -version`: 
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

2. Operating system: CentOS (server where Saiku was installed), Windows 10 family (my computer)

3. Browser and version (if relevant) : Firefox 69.0.1 (64 bits)

4. Saiku plugin to Pentaho or Saiku Standalone : Saiku Standalone

5. Saiku CE or Saiku EE : Saiku EE

6. Saiku version: Saiku Suite V2.1 GA
### Steps to Reproduce

When i’m editting a query and i want to switch cube, this following windows opens. So i press « Okay » to valide my choice but nothing happen : the windows is open again and i can't use the query tab.
![image](https://user-images.githubusercontent.com/55831858/65690633-c73a7700-e06f-11e9-9374-0079e40fa881.png)

Steps : 

1. Create a new query
2. Select a cube
![image](https://user-images.githubusercontent.com/55831858/65691569-57c58700-e071-11e9-89be-5f702f94f9dc.png)

3. Select an other cube
![image](https://user-images.githubusercontent.com/55831858/65691586-5eec9500-e071-11e9-9b95-577da532f85d.png)

4. Press "Okay" : Nothing happen
5. Press Cancel : I can't use the query tab and the data (measures and dimensions) are from the previous cube
![image](https://user-images.githubusercontent.com/55831858/65691633-76c41900-e071-11e9-9245-6ddea981a8de.png)

I don't know how is it possible. Maybe i need to activate or change a parameter !

Thanks for your help.

**Comment by brunogamacatao** [comment]
In order to help me fix this issue as soon as possible, can you please send me your browser's logs when this problem happens?
Using Chrome you can achieve this by pressing F12 (or right click on your webpage and selecting Inspect), then you click on 'Console' tab, reproduce the problem and copy the contents.
Currently there are several versions of Saiku running on different platforms, with patches developed for each client. Running the latest Saiku release I am able to switch between cubes, as the attached screen capture demonstrates.

[SwitchingCubes.zip](https://github.com/OSBI/saiku/files/3667432/SwitchingCubes.zip)

Thanks a lot.

**Comment by neolinkbb** [comment]
Hi,

This is the logs of when i press « Okay »
[cid:image001.png@01D57770.7293A9A0]
TypeError: this.extractDefaultFilters is not a function Workspace.js:520:31
    create_new_query https://saiku-cd.neolink.link/js/saiku/views/Workspace.js:520
    okay https://saiku-cd.neolink.link/js/saiku/views/WarningModal.js:55
    call https://saiku-cd.neolink.link/js/saiku/views/Modal.js:90
    call self-hosted:1003
    jQuery 2
        dispatch
        handle

Thanks and i hope it will help you.

Regards,

Blandine Bouchacourt
Data Analyst
22, rue Christophe Colomb – 41000 Blois
blandine.b@neolink.link<mailto:blandine.b@neolink.link>
[neolink]<https://www.neolink.link/>

De : Bruno Gama Catão <notifications@github.com>
Envoyé : dimanche 29 septembre 2019 16:17
À : OSBI/saiku <saiku@noreply.github.com>
Cc : Blandine BOUCHACOURT <blandine.b@neolink.link>; Author <author@noreply.github.com>
Objet : Re: [OSBI/saiku] I can't switch cube in the same query tab (#709)


In order to help me fix this issue as soon as possible, can you please send me your browser's logs when this problem happens?
Using Chrome you can achieve this by pressing F12 (or right click on your webpage and selecting Inspect), then you click on 'Console' tab, reproduce the problem and copy the contents.
Currently there are several versions of Saiku running on different platforms, with patches developed for each client. Running the latest Saiku release I am able to switch between cubes, as the attached screen capture demonstrates.

SwitchingCubes.zip<https://github.com/OSBI/saiku/files/3667432/SwitchingCubes.zip>

Thanks a lot.

**Comment by brunogamacatao** [comment]
Here's a fix for this problem, based of the logs. Please replace the file `SAIKU_DIR/server/tomcat/webapps/ROOT/js/saiku/views/Workspace.js` with the one in the zip package below:
[Workspace.zip](https://github.com/OSBI/saiku/files/3694595/Workspace.zip)
Please extract the contents of this zip file (githup does not allow posting plain js files, that why I've sent it inside a zip file) and put it inside the before mentioned directory.
The fixed file was also updated in SaikuEE repository.

**Comment by neolinkbb** [comment]
Hi Bruno,

Thanks it works.

Regards,

Blandine Bouchacourt
Data Analyst
22, rue Christophe Colomb – 41000 Blois
blandine.b@neolink.link<mailto:blandine.b@neolink.link>
[neolink]<https://www.neolink.link/>

De : Bruno Gama Catão <notifications@github.com>
Envoyé : dimanche 6 octobre 2019 17:54
À : OSBI/saiku <saiku@noreply.github.com>
Cc : Blandine BOUCHACOURT <blandine.b@neolink.link>; Author <author@noreply.github.com>
Objet : Re: [OSBI/saiku] I can't switch cube in the same query tab (#709)


Here's a fix for this problem, based of the logs. Please replace the file SAIKU_DIR/server/tomcat/webapps/ROOT/js/saiku/views/Workspace.js with the one in the zip package below:
Workspace.zip<https://github.com/OSBI/saiku/files/3694595/Workspace.zip>
Please extract the contents of this zip file (githup does not allow posting plain js files, that why I've sent it inside a zip file) and put it inside the before mentioned directory.
The fixed file was also updated in SaikuEE repository.
