### ISSUE TITLE
Broken links in read.me

### ISSUE THREAD

**Issue by LedaMC-izubiaurre** [OSBI/saiku#718]
The link provided in section _"Get Saiku License"_ of [README.md](https://github.com/OSBI/saiku/blob/development/README.md) doesn't provide the everlasting free license it mentions. Only a 30-day demo license is offered for free. Please update.

Following the provided link, Google Groups says that the Saiku User Group is closed (either for non-licensed users or at all). Please clarify in [README.md](https://github.com/OSBI/saiku/blob/development/README.md).

**Comment by brenopolanski** [comment]
Hey @LedaMC-izubiaurre is fixed now!
